CREATE TABLE GROUPS_USERS_LINKS (
	IDUSER INTEGER NOT NULL,
	IDGROUP INTEGER NOT NULL,
	CODE VARCHAR(40) NOT NULL,
	CONSTRAINT GROUPS_USERS_LINKS_FK FOREIGN KEY (IDGROUP) REFERENCES GROUPS(ID_GROUP),
	CONSTRAINT GROUPS_USERS_LINKS_FK_1 FOREIGN KEY (IDUSER) REFERENCES USERS(ID_USER)
);
CREATE INDEX GROUPS_USERS_LINKS_IDUSER_IDX ON GROUPS_USERS_LINKS (IDUSER);
CREATE INDEX GROUPS_USERS_LINKS_IDGROUP_IDX ON GROUPS_USERS_LINKS (IDGROUP);
