--ALTER TABLE USERS
--  ADD PHONE_NUMBER_M VARCHAR(20) CHARACTER SET UTF8;

--UPDATE USERS 
--  SET PHONE_NUMBER_M = PHONE_NUMBER;

--ALTER TABLE USERS DROP PHONE_NUMBER;

--ALTER TABLE USERS
--  ADD PHONE_NUMBER VARCHAR(20) CHARACTER SET UTF8;

--UPDATE USERS
--  SET PHONE_NUMBER = PHONE_NUMBER_M;

--ALTER TABLE USERS DROP PHONE_NUMBER_M;

--ALTER TABLE GROUP_INVITE 
--  ADD PHONE_NUMBER_M VARCHAR(20) CHARACTER SET UTF8;

--UPDATE GROUP_INVITE
--  SET PHONE_NUMBER_M = PHONE_NUMBER;

--ALTER TABLE GROUP_INVITE DROP PHONE_NUMBER;

--ALTER TABLE GROUP_INVITE
--  ADD PHONE_NUMBER VARCHAR(20) CHARACTER SET UTF8;

--UPDATE GROUP_INVITE
--  SET PHONE_NUMBER = PHONE_NUMBER_M;

--ALTER TABLE GROUP_INVITE DROP PHONE_NUMBER_M;