--ALTER TABLE MEETINGS
--  ADD REMINDER_MESSAGES_TIME INTEGER;

--ALTER TABLE MEETINGS
--  ADD LAST_REMINDER_MESSAGES_TIME TIMESTAMP;

--ALTER TABLE NOTIFICATION
--  ADD MEETING_REMINDER_NOTIFICATION BOOLEAN DEFAULT true NOT NULL;

--ALTER TABLE NOTIFICATION
--  ADD TIME_SILENT_START TIME;

--ALTER TABLE NOTIFICATION
--  ADD TIME_SILENT_END TIME;